### model
model_name_or_path: deepseek-ai/DeepSeek-R1-Distill-Qwen-7B
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 32
lora_target: all

### dataset
dataset: SVGX_SFT_GEN_basic_enc,SVGX_SFT_UN_basic_enc,SVGX_SFT_GEN_51k_enc
template: deepseek3
cutoff_len: 4096
max_samples: 20000000
overwrite_cache: true
preprocessing_num_workers: 128

### output
output_dir: saves/encode-code/deepseek-distill-qwen-lora-SVGX-sft
logging_steps: 50
save_steps: 2000
plot_loss: true
overwrite_output_dir: true1

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 3.0e-4
num_train_epochs: 5.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### generation
max_length: 4096
max_new_tokens: 4096

### eval
val_size: 0.02
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 2000