### model
model_name_or_path: google/gemma-3-12b-it
trust_remote_code: true
image_max_pixels: 262144

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 128
lora_target: all

### dataset
dataset: SVGX_SFT_GEN_basic,SVGX_SFT_UN_basic,SVGX_SFT_vision_25k_enc,SVGX_SFT_GEN_51k_enc
template: gemma3
cutoff_len: 4096
max_samples: 20000000
overwrite_cache: true
preprocessing_num_workers: 128

### output
output_dir: saves/encode-code/gemma3-12b-lora-SVGX-sft
logging_steps: 50
save_steps: 2000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 3.0e-4
num_train_epochs: 5.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### new tokens
new_special_tokens_config: data/SVGX-dataset/svg_tokens.yaml
init_special_tokens: semantic_init
skip_special_tokens: False

### generation
max_length: 4096
max_new_tokens: 4096

### eval
val_size: 0.02
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 2000
