name: llm4svg
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scipy
  - matplotlib
  - scikit-learn
  - pytorch=2.6.0
  - torchvision
  - torchaudio
  # Specify your desired CUDA toolkit version.
  # CUDA 12.4 is common.
  - pytorch-cuda=12.4
  - tqdm
  - requests
  - pip:
      - accelerate
      - datasets
      - trl
      - huggingface-hub
      - modelscope
      - einops
      - safetensors
      - hydra
      - omegaconf
      - lxml
      - tensorboard
      - cairosvg
      - unsloth